### ISSUE TITLE
No templates for raising issues or making pull requests

### ISSUE THREAD

**Issue by Alex-Yarkosky** [GatorEducator/gatorgradle#43]
Adding these templates should be considered in order to make it easier to contribute to this as an open source project and provide uniformity. The need for these are outlined [here](https://opensource.guide/). These files are also suggested on the [Community](https://github.com/GatorEducator/gatorgrader/community) page.

**Comment by gkapfham** [comment]
Hello @Alex-Yarkosky thanks for raising this issue. @Michionlion in the near future I will start to add some of the same templates that we use in GatorGrader for this project as well. Does that seem acceptable to you?

**Comment by gkapfham** [comment]
I wanted to note that these type of files now exist in the GatorGrader repository available at:

https://github.com/GatorEducator/gatorgrader

Note that since GatorGrader is a Python project some of the content would change. With that said, I don't think that we would need to change the code of conduct and it might be possible to adopt some more general-purpose Java programming guidelines for the documentation that explains the way to contribute to this project and how we use Java development tools.

**Comment by gkapfham** [comment]
Oh, @Alex-Yarkosky we could also introduce a standard for commit messages! There is also an example of this inside of the GatorGrader repository.

**Comment by gkapfham** [comment]
@Alex-Yarkosky do you want to tackle this issue?

**Comment by Michionlion** [comment]
Since this project is being put on ice in favor of [GatorGrade](https://github.com/GatorEducator/gatorgrade), this is no longer necessary.
