### ISSUE TITLE
Gradle 8.0 will remove functionality of deprecated executor.submit

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgradle#73]
Hi @Michionlion! When I use this GatorGradle with Gradle 7.2 I now see the following warning:

```
The WorkerExecutor.submit() method has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the noIsolation(), classLoaderIsolation() or processIsolation() method instead. See https://docs.gradle.org/7.2/userguide/upgrading_version_5.html#method_workerexecutor_submit_is_deprecated for more details.
```
I think that this is due to the fact that this source code:

```
        // configure command executor
        executor.submit(CommandExecutor.class, (conf) -> {
          conf.setIsolationMode(IsolationMode.NONE);
          conf.setDisplayName(cmd.toString());
          conf.setParams(cmd);
        });
      }
```

exists inside of the `GatorGraderGradeTask.java` file. Is this an easy fix @Michionlion?

As a follow-on, but longer-term question, what do you think about implementing a pure-Python solution for running tasks and then integrating it directly inside of GatorGrader. I know that you are busy with many other tasks but if you ever have time to share feedback and ideas, your help would be greatly appreciated. Thanks!

It is worth noting that `gradle grade` still works correctly. However, it produces this diagnostic message as long as you are using a recent version of `gradle`.

**Comment by Michionlion** [comment]
From a quick and cursory look at the [documentation](https://docs.gradle.org/current/javadoc/org/gradle/workers/WorkerExecutor.html), it looks like `executor.submit` can be replaced with `executor.noIsolation().submit`, which should resolve this issue. The `setIsolationMode()` method call would need to be removed as well.

**Comment by Michionlion** [comment]
Additionally, I do think a pure-python solution would be good! We should think about what method of invocation and dependency management we would use, since we'd also need to replace those parts of GatorGradle.

**Comment by gkapfham** [comment]
Hi @Michionlion, yes, I agree that we should think more about a pure-Python solution. I have already thought through some trade-offs and I have some ideas for at least one potential design.

**Comment by Michionlion** [comment]
I do have to say that I was looking at the example repositories we have now, and they make setting up GatorGradle seem very complicated because there is a lot of unneeded configuration. In fact, all that is actually needed for a fully-fledged setup is a `build.gradle` like below, and a `gatorgrader.yml` that just contains whatever checks you want.
```
plugins {
  id "org.gatored.gatorgradle" version "0.5.1"
}
```

I think that for the near-term future a pure-python solution isn't a good place to put development time, and it would be better to focus that time on other tools or additional checks for GatorGrader. When we do get around to doing something, we should strive to have it be even simpler than the above -- hopefully only a `gatorgrader.yml` (that maybe can reference/include a remote file to keep grading checks separate from student repositories) and an executable that can be `pip` installed.
